services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - '5000:5000'
    networks:
      - app-network
    env_file:
      - ./client/.env
    develop:
      watch:
        - path: ./client/src
          target: /usr/src/app/src
          action: sync

  data-fetcher:
    build:
      context: ./news-api
      dockerfile: apps/data-fetcher/Dockerfile
      target: development
    container_name: data-fetcher
    depends_on:
      - db
      - rmq
      - redis
    command: npm run start:dev data-fetcher
    env_file:
      - ./news-api/apps/data-fetcher/.env
    volumes:
      - /usr/src/app/node_modules
    networks:
      - app-network
    ports:
      - '3000:3000'
    develop:
      watch:
        - path: ./news-api/apps/data-fetcher
          target: /usr/src/app/apps/data-fetcher
          action: sync

  search-delivery:
    build:
      context: ./news-api
      dockerfile: apps/search-delivery/Dockerfile
      target: development
    container_name: search-delivery
    depends_on:
      - db
      - rmq
      - redis
    command: npm run start:dev search-delivery
    env_file:
      - ./news-api/apps/search-delivery/.env
    volumes:
      - /usr/src/app/node_modules
    networks:
      - app-network
    ports:
      - '3001:3001'
    develop:
      watch:
        - path: ./news-api/apps/search-delivery
          target: /usr/src/app/apps/search-delivery
          action: sync

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    env_file: '.env'
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  rmq:
    image: rabbitmq:4-management-alpine
    container_name: rmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network
      - rmq_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    env_file: ".env"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    ports:
      - '6379:6379'
    networks:
      - app-network
    volumes:
      - redisdata:/data

volumes:
  pgdata:
    driver: local

  redisdata:
    driver: local

networks:
  app-network:
    driver: bridge

  rmq_network:
    driver: bridge
