services:
  data-fetcher:
    build:
      context: .
      dockerfile: ./apps/data-fetcher/Dockerfile
      target: development
    container_name: data-fetcher
    depends_on:
      - db
    command: npm run start:dev data-fetcher
    env_file:
      - ./apps/data-fetcher/.env
    volumes:
      - /usr/src/app/node_modules
    networks:
      - app-network
    ports:
      - '3000:3000'
    develop:
      watch:
        - path: ./apps/data-fetcher
          target: /usr/src/app/apps/data-fetcher
          action: sync

  search-delivery:
    build:
      context: .
      dockerfile: ./apps/search-delivery/Dockerfile
      target: development
    container_name: search-delivery
    depends_on:
      - db
    command: npm run start:dev search-delivery
    env_file:
      - ./apps/search-delivery/.env
    volumes:
      - /usr/src/app/node_modules
    networks:
      - app-network
    ports:
      - '3001:3001'
    develop:
      watch:
        - path: ./apps/search-delivery
          target: /usr/src/app/apps/search-delivery
          action: sync

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
      - '5433:5432'
    env_file: '.env'
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  rmq:
    image: rabbitmq:4-management-alpine
    container_name: rmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - app-network
      - rmq_network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge

  rmq_network:
    driver: bridge
